
const jokes = [
  "Knock knock. Who’s there? Lettuce. Lettuce who? Lettuce in, it’s freezing out here!",
  "Knock knock. Who’s there? Boo. Boo who? Don’t cry, it’s just a joke!",
  "Knock knock. Who’s there? Cow says. Cow says who? Cow says moooo!",
  "Knock knock. Who’s there? Atch. Atch who? Bless you!",
  "Knock knock. Who’s there? Annie. Annie who? Annie way you can let me in now?",
  "Knock knock. Who’s there? Harry. Harry who? Harry up and answer the door!",
  "Knock knock. Who’s there? Orange. Orange who? Orange you going to let me in?",
  "Knock knock. Who’s there? Banana. Banana who? Banana split so ice creamed!",
  "Knock knock. Who’s there? Olive. Olive who? Olive you and I miss you!",
  "Knock knock. Who’s there? Honeydew. Honeydew who? Honeydew you know how sweet you are?",
  "Knock knock. Who’s there? Ice cream. Ice cream who? Ice cream if you don’t let me in!",
  "Knock knock. Who’s there? Tank. Tank who? You’re welcome!",
  "Knock knock. Who’s there? Dozen. Dozen who? Dozen anyone want to let me in?",
  "Knock knock. Who’s there? Dewey. Dewey who? Dewey have to keep doing this?",
  "Knock knock. Who’s there? Europe. Europe who? No, YOU'RE a poo!",
  "Knock knock. Who’s there? Candice. Candice who? Candice joke get any worse?",
  "Knock knock. Who’s there? Figs. Figs who? Figs the doorbell, it’s broken!",
  "Knock knock. Who’s there? Police. Police who? Police let us in, it’s cold out here!",
  "Knock knock. Who’s there? Canoe. Canoe who? Canoe come out and play with me?",
  "Knock knock. Who’s there? Beets. Beets who? Beets me!",
  "Knock knock. Who’s there? Alpaca. Alpaca who? Alpaca the suitcase, you load up the car!",
  "Knock knock. Who’s there? Butter. Butter who? Butter let me in or I’ll freeze!",
  "Knock knock. Who’s there? Howard. Howard who? Howard you like a nice cold drink?",
  "Knock knock. Who’s there? Broken pencil. Broken pencil who? Never mind, it’s pointless!",
  "Knock knock. Who’s there? Donut. Donut who? Donut forget to open the door!",
  "Knock knock. Who’s there? Theodore. Theodore who? Theodore wasn’t open, so I knocked!",
  "Knock knock. Who’s there? Stopwatch. Stopwatch who? Stopwatch you’re doing and open up!",
  "Knock knock. Who’s there? Snow. Snow who? Snow use, the joke is over!",
  "Knock knock. Who’s there? Harry. Harry who? Harry up and answer the door!",
  "Knock knock. Who’s there? Dishes. Dishes who? Dishes the police, open up!",
  "Knock knock. Who’s there? A little old lady. A little old lady who? I didn’t know you could yodel!",
  "Knock knock. Who’s there? Wooden shoe. Wooden shoe who? Wooden shoe like to hear another joke?",
  "Knock knock. Who’s there? Yukon. Yukon who? Yukon go ahead and let me in!",
  "Knock knock. Who’s there? Ice cream. Ice cream who? Ice cream if you don’t let me in!",
  "Knock knock. Who’s there? Nobel. Nobel who? Nobel, that’s why I knocked!",
  "Knock knock. Who’s there? Tank. Tank who? You’re welcome!",
  "Knock knock. Who’s there? Luke. Luke who? Luke through the peephole and find out!",
  "Knock knock. Who’s there? Annie. Annie who? Annie way you can let me in now?",
  "Knock knock. Who’s there? Owls. Owls who? Yes, they do!",
  "Knock knock. Who’s there? Kenya. Kenya who? Kenya let me in already?",
  "Knock knock. Who’s there? Cows go. Cows go who? No, silly. Cows go moo!",
  "Knock knock. Who’s there? Butter. Butter who? Butter open up, it’s cold out here!",
  "Knock knock. Who’s there? Boo. Boo who? Don't cry, it's just a joke!",
  "Knock knock. Who’s there? Figs. Figs who? Figs the doorbell, it’s broken!",
  "Knock knock. Who’s there? Lettuce. Lettuce who? Lettuce in, we’re freezing out here!",
  "Knock knock. Who’s there? Candice. Candice who? Candice joke get any worse?",
  "Knock knock. Who’s there? Honeydew. Honeydew who? Honeydew you know how sweet you are?",
  "Knock knock. Who’s there? Ice cream. Ice cream who? Ice cream if you don’t let me in!",
  "Knock knock. Who’s there? Dozen. Dozen who? Dozen anyone want to let me in?",
];

export default jokes;
